#!/bin/awk -f

#############################################
# このファイルはaccessKeys.csvファイルを        #
# aws profileの形式に変換するためのスクリプトです #
#############################################
## コマンド例
## awk -f {このスクリプト名} {awsプロファイル名} < {アクセスcsvファイル} >> ~/.aws/credentials
### 補足
### accessキーではなく、ユーザー作成時の認証情報であれば以下のコマンドで読み取り可能(v2以降)
### aws configure import --csv  file://{ファイルPATH}

BEGIN {
    FS=","
    # profile name i.e. ini header
    header="[" ARGV[1] "]"
    ARGV[1]=""
    print header
}
# only process line 2 of CSV
FNR==2 {
    print "aws_access_key_id=" $1
    print "aws_secret_access_key=" $2
}